tripleee/sloshy

sloshy.yaml
- Added "Physics questions at MMSE"
- Added "Chemistry questions at MMSE"
=> Added two rooms

sloshy.yaml
=> sloshy.yaml: Remove frozen room 111121

README.md, scrape_chat.py, sloshy.py, sloshy.yaml, test-pushed.yaml
scrape_chat.py: refactor some of the existing code and add a search method
sloshy.py: update YAML schema to 20211215, with migration for old config
sloshy.yaml: configuration thusly migrated, add Sloshy's chat ID for each server
README.md: update documentation; note breaking change
Partially fixes: #20
Partially fixes: #21
Fixes: #11
=> Implement --announce feature to check write access to any new rooms

sloshy.yaml
add "Sustainable Living" (https://chat.stackexchange.com/rooms/7310/sustainable-living) to the no-freeze list
It was suggested in chat, here: https://chat.stackexchange.com/transcript/message/61176987#61176987
Just [follow the README](https://github.com/tripleee/sloshy/blob/master/README.md#configuration)
=> add Sustainable Living chat

sloshy.yaml
OR has has a surge in the visits/day metric lately, and this room is used to help study what's contributing to the surge.
=> Added HNQ chat room for Operations Research

sloshy.yaml
1) Stack Overflow: Meta Python
2) Signal Processing: General Discussion
3) Signal Processing: Toptica FFT
=> Added three rooms

sloshy.yaml
Requesting that sloshy keep SE.SP "Post-Processing" chat from being frozen, as per Noodle's request. Let me know if I've done this correctly.
=> SE.SP mod request

sloshy.yaml
Permission was obtained from Samuel Liew (diamond mod on SO) here: https://chat.stackoverflow.com/transcript/message/56043467#56043467, after a thorough explanation of what Sloshy does.
=> Add ElectionBot (SO) room.

sloshy.yaml
As discussed in chat: https://chat.stackoverflow.com/transcript/message/56221542#56221542
=> sloshy.yaml: add CV-PLS old questions room

sloshy.yaml
=> sloshy.yaml: Add Operations Research: General

sloshy.yaml
Approved by the RO: https://chat.stackoverflow.com/transcript/message/56277450
=> Adding R Language Collective chatroom to Sloshy

sloshy.yaml
Add CV-PLS OQ requests graveyard;
Add CV-PLS OQ /dev/null
I have given Sloshy explicit write access in both rooms.
=> sloshy.yaml: add CV-PLS OQ graveyard and dev/null

sloshy.yaml
https://chat.stackexchange.com/rooms/146039/ai-stuff
Yes, this is me.
=> Add AI stuff room

README.md, sloshy.py, sloshy.yaml
Add back SOBotics as a "cc" room which only receives action notifications
(Closes: #58)
=> "Cc" room feature (schema 20230827); SOBotics as "cc" room

sloshy.yaml
Requested by V2Blast: https://chat.stackexchange.com/transcript/message/64383260#64383260
=> sloshy.yaml: add Area 51 main room

sloshy.yaml
Regulars are posting "keep alive" notices, let's let them stop doing that
=> sloshy.yaml: add #!/bin/bash room on SO

.github/workflows/pr-builder.yml, README.md, sloshy.py, sloshy.yaml
Unfortunately, the usability of this is quite atrocious; but hey, it works.
=> PR builder - Github Action to create YAML PRs

sloshy.yaml
https://chat.stackexchange.com/transcript/message/64778465#64778465
=> Add You Are Here

sloshy.yaml
Add Bad Stack Overflow Reviews to the list [by request](https://chat.stackoverflow.com/transcript/message/56995966).
=> Update sloshy.yaml: Add Bad SO Reviews room

.github/workflows/nightly.yml, README.md
README.md: add status badge for same
Also, link to Toasty
=> .github/workflows/nightly.yml: add healthchecks.io check

scrape_chat.py, sloshy.py
scrape_chat.py: actual reputation check implementation; refactor to base class SloshyClient for the basic User-Agent etc
Hopefully prevent #73 from happening again
=> sloshy.py: perform reputation check before attempting to log in

sloshy.yaml
As a room owner of [The Tarpit](https://chat.stackexchange.com/rooms/info/110136/the-tarpit), I would like Sloshy to antifreeze the room so I can talk about esoteric programming languages there whenever the mood strikes.
=> Add The Tarpit

.circleci/config.yml
Port over actions from .github/workflows/test-pushed.yml
=> .circleci/config.yml: add test for pushed code

.circleci/config.yml, run.py, sloshy.py
Indicate CircleCI as the location for the related workflows (and Github Actions for the legacy nightly)
=> Add --location_extra option

.circleci/config.yml
Removed trigger from web UI; try to avoid mixing nightly and pushed runs
=> .circleci/config.yml: configure explicit scheduled trigger

sloshy.yaml
There are a few which were frozen already so no way to take on those at the moment
=> sloshy.yaml: add Toasty's rooms for the time being

sloshy.py
In preparation for #78 and maybe #87, add diagnostics to identify slow rooms
=> Add timing information for each room; summary with slowest rooms

.circleci/config.yml, scrape_chat.py, sloshy.py
=> --no-slow-summary option + debugging for transcript

scrape_chat.py
Requests provides a retry handler which obeys the Retry-After: header if present
=> scrape_chat.py: Hook in proper 429 retry handler

README.md
Also, renumber numbered links for consistency
=> README.md: redirect status shields to Github Actions

scrape_chat.py, sloshy.py
=> Require properly adjacent Sloshy messages for optimized room scanning

requirements.txt
Experimentally bump to a version with additional 429 handling
=> requirements.txt: private 429-handler branch of ChatExhange

scrape_chat.py
Catch errors from `strptime` and show the offending value in logs.
=> Debugging for #108

scrape_chat.py
Duh, I added debugging for the wrong strptime in the previous PR!
=> More debugging for #108

scrape_chat.py
Teach me to test the code before committing
=> Yet still more additional debugging for #108

sloshy.py
=> sloshy.py: increase sleep after 429 failures to 600 seconds

run.py, sloshy.py
Might make a difference for #103
=> --randomize option to shuffle room order; use this for nightly

sloshy.yaml
Requested by galacticninja
https://chat.stackexchange.com/transcript/message/66460121#66460121
=> Add Web Apps SE moderator discussion
